---
- name: Check running service for windows 
  hosts: all
  tasks:
    - name: Get info of Windows VM
      ansible.windows.win_service_info:
        name: WinRM
      register: service_info
      

    - name: print status of service
      ansible.builtin.debug: 
        var: service_info 