---
- name: Output time every min
  hosts: all
  become: yes

  tasks:
    - name: Output the current time
      ansible.builtin.command: date
      register: result
      loop: "{{ range(60) | list }}"
      delay: 60

    - name: Print the current time
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
      loop: "{{ range(60) | list }}"