---
- name: Output time every min
  hosts: all
  become: yes

  tasks:
    - name: Output the time
      ansible.builtin.command: date
      register: date_output
      
    - name: Print the time
      ansible.builtin.debug:
        msg: "{{ date_output.stdout }}"

