---
- name: Output time every min
  hosts: all
  become: yes

  tasks:
    - name: Print the current time
      ansible.builtin.shell: date
      register: current_time
      
    - name: Print the current time every minute
      ansible.builtin.debug:
        msg: "{{ current_time.stdout }}"
      loop: "{{ range(1, 60) | list }}"
      loop_control:
        pause: 60