---
- name: Output time every min
  hosts: all
  become: yes

  tasks:
    - name: Print the time
      ansible.builtin.command: date
      register: result
      changed_when: false
      
    - name: Output the time every minute
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
      loop: "{{ range(1, 60) | list }}"
      loop_control:
        pause: 60
