---
- name: Taking VM Snapshot
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Take VM Snapshot
      ansible.builtin.shell: "sudo virsh snapshot-create-as --domain 'win2019' --name 'windowSS-1'"
      register: vm_snapshot_result
      ignore_errors: true
