---
- name: Taking VM Snapshot
  hosts: all
  become: yes
  gather_facts: no
  vars:
    - inventory
  tasks:

    - name: Take VM Snapshot
      ansible.builtin.shell: "virsh snapshot-create-as --domain 'win2019' --name 'windowSS-1'"
      register: vm_snapshot_result
      delegate_to: 192.168.122.1
      ignore_errors: true

    - name: VM snapshot result
      ansible.builtin.debug:
        var: vm_snapshot_result