---
- name: Taking VM Snapshot
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Getting date and time
      ansible.builtin.set_stats:
        data:              
          end_time: "{{ lookup('pipe','date \"+%T %Z %F\"') }}"
      delegate_to: vm_host
      delegate_facts: true
      run_once: true


    - name: Take VM Snapshot
      ansible.builtin.shell: "virsh snapshot-create-as --domain {{ kvm_vm_name }} --name {{ kvm_vm_name }}_{{ end_time }}"
      register: vm_snapshot_result
      delegate_to: vm_host
      ignore_errors: true


