---
- name: Taking VM Snapshot
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Getting date and time
      ansible.builtin.set_fact:
        datetime: "{{ ansible_date_time.date }}_{{ ansible_date_time.time |  replace(':','-') }}" 
        end_time: "{{ lookup('pipe','date \"+%T %Z %F\"') }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true
      register: snapshot_name

    - name: Take VM Snapshot
      ansible.builtin.shell: "sudo virsh snapshot-create-as --domain {{ kvm_vm_name }} --name {{ snapshot_name }}"
      delegate_to: vm_host
      register: vm_snapshot_result
      ignore_errors: true


