---
- name: Taking VM Snapshot
  hosts: all
  become: yes

  tasks:

    - name: Getting date and time
      ansible.builtin.set_fact:
        datetime: "{{ ansible_date_time.date }}_{{ ansible_date_time.time |  replace(':','-') }}" 
        end_time: "{{ lookup('pipe','date \"+%T %Z %F\"') }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true

    - name: Take VM Snapshot
      ansible.builtin.shell: "sudo virsh snapshot-create-as --domain {{ kvm_vm_name }} --name {{ kvm_vm_name }}.datetime.end_time"
      register: vm_snapshot_result
      delegate_to: Windows
      ignore_errors: true


