---
- name: Taking VM Snapshot
  hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Take VM Snapshot
      ansible.builtin.shell: "virsh snapshot-create-as --domain {{ kvm_vm_name }} --name 'windowSS-1'"
      register: vm_snapshot_result
      delegate_to: vm_host
      ignore_errors: true

    - name: VM snapshot result
      ansible.builtin.debug:
        var: vm_snapshot_result