---
- name: Windows rolling update
  hosts: all
  tasks:

  #Precheck
  - name: Get running services of Windows VM
    ansible.windows.win_service_info:
      register: service_info  

  #Patching
  - name: Run updates on windows
    ansible.windows.win_updates:
      category_names: '*'
      state: installed
      #reboot: true
    register: ansible_update

  - name: report results
    ansible.builtin.set_stats:
        data: 
          ansible_update_kb: "{{ ansible_update.updates | dict2items| selectattr('value.installed', 'equalto', true) | map(attribute='value.kb') | list }}"

  #Reboot
  - name: Reboot windows and wait for 100 seconds
    ansible.windows.win_reboot:
      reboot_timeout: 100
    
  #Postcheck
  - name: Get running services of Windows VM
    ansible.windows.win_service_info:
    register: service_info2  