---
- name: Windows rolling update
  hosts: all
  tasks:

  - name: Run updates on windows
    ansible.windows.win_updates:
      category_names: '*'
      state: installed
      reboot: true
      log_path: C:\ansibleUpdates.txt