---
- name: Check running service for windows 
  hosts: all

  tasks:
    - name: Get running services of Windows VM
      ansible.windows.win_service_info:
      register: service_info

    - name: Print running service on Windows
      ansible.builtin.debug:
        msg: " {{ item.display_name }} has started "
      loop: "{{ service_info.services }}"
      when: item.state == 'started'

    - name: Check disk space on Windows
      ansible.windows.win_shell: 'Get-PSDrive C | Select-Object Free | ft -HideTableHeaders'
      register: windows_disk_space

    - name: convert string to integer
      ansible.builtin.set_fact:
        windows_disk_space_int: "{{ windows_disk_space.stdout | int }}"
          
    - name: if not enough space
      ansible.builtin.debug:
        msg: "There is less than 2GB of free space"
      when: windows_disk_space_int > '2000000000'
    
    - name: Print disk space on Windows
      ansible.builtin.debug:
        var: windows_disk_space

    - name: Search-only, return list of found updates 
      ansible.windows.win_updates:
        category_names: '*'
        state: searched
      register: ansible_checks
  
    - name: report results
      ansible.builtin.debug:
        msg: |
          {% for k in ansible_checks %}
          {{ ansible_checks[k].title }}
          kb: {{ ansible_checks.kb }}
          Installed status: {{ ansible_checks.is_installed }}
          {% endfor %}



