---
- name: Post Patch Checks
  hosts: all
  
  tasks: 
  - name: Get running services of Windows VM
    ansible.windows.win_service_info:
    register: service_info2  

  - name: Create a list of running services
    ansible.builtin.set_fact:
      service_info2_running: "{{ service_info2.services | selectattr('state', 'equalto', 'started') | map(attribute='display_name') | list }}"

  - name: compare pre chk vs post chk
    ansible.builtin.debug: 
      diff: "{{ service_info_running | ansible.builtin.intersect(service_info2_running) }}"

  - name: Generate a Post-Patch HTML report
    ansible.builtin.template:
      src: postreport.html.j2
      dest: /postreport.html