---
- name: Post Patch Checks
  hosts: all
  
  tasks: 
  - name: Check running services
    ansible.windows.win_service_info:
      name: WinRM
    register: service_info

  - name: compare pre chk vs post chk
    ansible.builtin.copy:
      src: C:\ansibleChecks.txt
      dest: C:\ansibleUpdates.txt
    check_mode: yes
    diff: yes

  - name: Generate a Post-Patch HTML report
    ansible.builtin.template:
      src: postreport.html.j2
      dest: /postreport.html