---
- name: Check running service for windows 
  hosts: all

  tasks:
    - name: Get running services of Windows VM
      ansible.windows.win_service_info:
      register: service_info  

    - name: Create a list of running services
      ansible.builtin.set_stats:
        data:
          service_info_running: "{{ service_info.services | selectattr('state', 'equalto', 'started') | map(attribute='display_name') | list }}"
       
    - name: Check disk space on Windows
      ansible.windows.win_shell: 'Get-PSDrive C | Select-Object Free | ft -HideTableHeaders'
      register: windows_disk_space

    - name: convert string to integer
      ansible.builtin.set_fact:
        windows_disk_space_int: "{{ windows_disk_space.stdout | int }}"
          
    - name: if not enough space
      ansible.builtin.debug:
        msg: "There is less than 2GB of free space"
      when: windows_disk_space_int < '2000000000'

    - name: Search-only, return list of found updates 
      ansible.windows.win_updates:
        category_names: '*'
        state: searched
      register: ansible_checks
  
    - name: Create list of kb in precheck
      ansible.builtin.set_stats:
        data: 
          ansible_checks_kb: "{{ ansible_checks.updates | dict2items| selectattr('value.installed'  | bool) | map(attribute='value.kb') | list }}"
#          ansible_checks_kb: "{{ ansible_checks.updates | dict2items | map(attribute='value.kb') | list }}" 