---
- name: Windows rolling update
  hosts: all
  tasks:

  - name: Run updates on windows
    ansible.windows.win_updates:
      category_names: '*'
      state: installed
      reboot: true
    register: ansible_update

  - name: report results
    ansible.builtin.debug:
      msg: |
        {% for k in ansible_update.updates %}
        {{ ansible_update.updates[k].title }}
        kb: {{ ansible_update.updates[k].kb }}
        Installed status: {{ ansible_update.updates[k].installed }}
        {% endfor %}
 