---
- name: Windows rolling update
  hosts: "{{ snapshot_ok_vms }}"
  tasks:

  - name: Run updates on windows
    ansible.windows.win_updates:
      category_names: '*'
      state: installed
      reboot: true
    register: ansible_update
    
  - name: report results
    ansible.builtin.set_stats:
        data: 
          ansible_update_kb: "{{ ansible_update.updates | dict2items | selectattr('installed', 'equalto', 'true') | map(attribute='value.kb') | list }}"
 