---
- name: Check running service for windows 
  hosts: all
  tasks:
    - name: Get running services of Windows VM
      ansible.windows.win_service_info:
        name: WinRM
      register: service_info

    - name: print status of service
      ansible.builtin.debug: 
        var: service_info 

    - name: Check disk space on Windows
      ansible.windows.win_shell: 'Get-PSDrive C | Select-Object Free | ft -HideTableHeaders'
      register: windows_disk_space
    
    - block:
        - name: if not enough space
          ansible.builtin.debug:
            msg: "There is less than 2GB of free space"
      when: windows_disk_space == '2000000000'
    
    - name: Print disk space on Windows
      ansible.builtin.debug:
        var: windows_disk_space

    - name: Search-only, return list of found updates (if any), log to C:\ansibleChecks.txt
      ansible.windows.win_updates:
        category_names: SecurityUpdates
        state: searched
        log_path: C:\ansibleChecks.txt

    - name: Take KVM snapshot of Windows VM
      community.libvirt.virt:
        name: WIN-VGPG44RLACLL
        state: snapshot
        snapshot: "{{ snapshot_name }}"
      vars:
        snapshot_name: "snapshot_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"

