---
- name: Check running service for windows 
  hosts: windows

  tasks:
    - name: Get running services of Windows VM
      ansible.windows.win_service_info:
      register: service_info
      when: service_info.services == started

    - name: Check disk space on Windows
      ansible.windows.win_shell: 'Get-PSDrive C | Select-Object Free | ft -HideTableHeaders'
      register: windows_disk_space
    
    - block:
        - name: if not enough space
          ansible.builtin.debug:
            msg: "There is less than 2GB of free space"
      when: windows_disk_space.size > '2000000000'
    
    - name: Print disk space on Windows
      ansible.builtin.debug:
        var: windows_disk_space

    - name: Search-only, return list of found updates 
      ansible.windows.win_updates:
        category_names: '*'
        state: searched
      register: ansible_checks
  
    - name: report results
      ansible.builtin.debug:
        msg: 
        {{ ansible_checks.title }}
        kb: {{ ansible_checks.kb }}
        Installed status: {{ ansible_checks.is_installed }}



