---
- name: Post Patch Checks
  hosts: all
  
  tasks: 
  - name: Check running services
    ansible.windows.win_service_info:
    register: service_info2

  - name: Print running service on Windows
    ansible.builtin.debug:
      msg: " {{ item.display_name }} has started "
    loop: "{{ service_info2.services }}"
    when: item.state == 'started'

  - name: compare pre chk vs post chk
    ansible.builtin.copy:
      src: C:\ansibleChecks.txt
      dest: C:\ansibleUpdates.txt
    check_mode: yes
    diff: yes

  - name: Generate a Post-Patch HTML report
    ansible.builtin.template:
      src: postreport.html.j2
      dest: /postreport.html