---
- name: Windows rolling update
  hosts: all
  tasks:

  - name: Run updates on windows
    ansible.windows.win_updates:
      category_names: '*'
      state: installed
      reboot: true
    register: ansible_update

  - name: report results
    ansible.builtin.set_stats:
        data: 
          ansible_update_kb: "{{ ansible_update.updates | dict2items | map(attribute='value.kb') | list }}"
 