---
- name: Check updates for window 
  hosts: all
  tasks:

    - name: Search-only, return list of found updates (if any)
      ansible.windows.win_updates:
        category_names: SecurityUpdates
        state: searched
        