---
collections:
  - name: ansible.utils
  - name: ansible.netcommon
  - name: https://github.com/redhat-cop/network.base.git
    type: git
    version: main
  - name: https://github.com/redhat-cop/network.telemetry.git
    type: git
    version: main