---
- name: Retrieve OS users from rhel
  hosts: all

  tasks:
    - name: retrive info for users
      ansible.builtin.command: getent passwd
      register: users_info

    - name: Extract usernames
      ansible.builtin.set_fact:
        users_list: "{{ users_info.stdout_lines | map('split', ':') | map('first') }}"

    - name: Get groups for each user
      ansible.builtin.shell: "id -Gn {{ item }}"
      register: user_groups
      loop: "{{ users_list }}"
      changed_when: false

    - name: Initialize the user statuses list
      ansible.builtin.set_fact:
        user_statuses_list: []

    - name: Check status of each user
      ansible.builtin.shell: |
        passwd_status=$(passwd -S {{ item }})
        if echo "$passwd_status" | grep -q " L "; then
          echo "User {{ item }} is locked/disabled."
        else
          echo "User {{ item }} is active."
        fi
      loop: "{{ users_list }}"
      register: user_statuses

    - name: Append each user status to the list
      ansible.builtin.set_fact:
        user_statuses_list: "{{ user_statuses_list + [item.stdout] }}"
      loop: "{{ user_statuses.results }}"

    - name: Display users, their groups, and statuses
      ansible.builtin.debug:
        msg: |
          {% for user, groups, status in users_list, user_groups.results, user_statuses.results %}
          User: {{ user }}
          Groups: {{ groups.stdout }}
          Status: {{ status.stdout.split()[2] | regex_replace('is', '') }}
          {% endfor %}