---
- name: Retrieve OS users from rhel
  hosts: all

  tasks:
    - name: retrive info for users
      ansible.builtin.getent:
        database: passwd

    - name: retrive info for groups
      ansible.builtin.getent:
        database: group

    - name: Get list of all users
      shell: |
        getent passwd | awk -F: '{ print $1 }'
      register: all_users

    - name: Check status of each user
      shell: |
        passwd_status=$(passwd -S {{ item }})
        if echo "$passwd_status" | grep -q " L "; then
          echo "User {{ item }} is locked/disabled."
        else
          echo "User {{ item }} is active."
        fi
      loop: "{{ all_users.stdout_lines }}"
      register: user_statuses

    - name: Display user statuses
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ user_statuses.results }}"
