---
- name: Retrieve OS users from rhel
  hosts: all

  tasks:
    - name: retrive info for users
      ansible.builtin.getent:
        database: passwd
      register: users_info

    - name: Convert user info to list of dictionaries
      ansible.builtin.set_fact:
        users_list: "{{ users_info.ansible_facts.getent_passwd | dict2items }}"

    - name: retrive info for groups
      ansible.builtin.getent:
        database: group
      register: groups_info

    - name: Display users and their groups
      ansible.builtin.debug:
        msg: "User {{ item.key }} belongs to groups {{ groups_info.stdout_lines | select('search', '^{{ item.key }}:') | map('regex_replace', '.*?:') | first }}"
      loop: "{{ users_list }}"

    - name: Initialize the user statuses list
      ansible.builtin.set_fact:
        user_statuses_list: []

    - name: Get list of all users
      ansible.builtin.shell: |
        getent passwd | awk -F: '{ print $1 }'
      register: all_users

    - name: Check status of each user
      ansible.builtin.shell: |
        passwd_status=$(passwd -S {{ item }})
        if echo "$passwd_status" | grep -q " L "; then
          echo "User {{ item }} is locked/disabled."
        else
          echo "User {{ item }} is active."
        fi
      loop: "{{ all_users.stdout_lines }}"
      register: user_statuses

    - name: Append each user status to the list
      ansible.builtin.set_fact:
        user_statuses_list: "{{ user_statuses_list + [item.stdout] }}"
      loop: "{{ user_statuses.results }}"

    - name: Display all user statuses together
      ansible.builtin.debug:
        msg: "{{ user_statuses_list }}"
