---
- name: Retrieve OS users from rhel
  hosts: all

  tasks:
    - name: retrive info for users
      ansible.builtin.getent:
        database: passwd
      register: users_info

    - name: retrive info for groups
      ansible.builtin.getent:
        database: group
      register: groups_info

    - name: Convert group info to list of dictionaries
      ansible.builtin.set_fact:
        groups_list: "{{ groups_info.ansible_facts.getent_group | dict2items }}"

    - name: Display users and their groups
      ansible.builtin.debug:
        msg: "User {{ user.key }} belongs to groups {{ groups_list | selectattr('value.3', 'search', user.key) | map(attribute='key') | list }}"
      loop: "{{ users_info.ansible_facts.getent_passwd | dict2items }}"
      loop_control:
        loop_var: user

    - name: Initialize the user statuses list
      ansible.builtin.set_fact:
        user_statuses_list: []

    - name: Get list of all users
      ansible.builtin.shell: |
        getent passwd | awk -F: '{ print $1 }'
      register: all_users

    - name: Check status of each user
      ansible.builtin.shell: |
        passwd_status=$(passwd -S {{ item }})
        if echo "$passwd_status" | grep -q " L "; then
          echo "User {{ item }} is locked/disabled."
        else
          echo "User {{ item }} is active."
        fi
      loop: "{{ all_users.stdout_lines }}"
      register: user_statuses

    - name: Append each user status to the list
      ansible.builtin.set_fact:
        user_statuses_list: "{{ user_statuses_list + [item.stdout] }}"
      loop: "{{ user_statuses.results }}"

    - name: Display all user statuses together
      ansible.builtin.debug:
        msg: "{{ user_statuses_list }}"
