---
- name: Retrieve OS users from rhel
  hosts: all

  tasks:
    - name: retrive info for users
      ansible.builtin.getent:
        database: passwd

    - name: retrive info for groups
      ansible.builtin.getent:
        database: group


