---
- name: Retrieve OS users from windows
  hosts: all

  tasks:
    - name: retrive info
      ansible.windows.win_whoami:
        
    - name: retreive group
      ansible.windows.win_group_membership: