---
- name: Retrieve OS users from windows
  hosts: all

  tasks:
    - name: retrive info of list of user
      ansible.windows.win_powershell:
        script: Get-LocalUser | Select-Object name
      register: local_users

    - name: retrive info of groups
      ansible.windows.win_powershell:
        script: Get-LocalGroup

    - name: list of groups of the users listed
      ansible.windows.win_powershell:
        script: Get-LocalUser | ForEach-Object { $user = $_ $groups = Get-LocalGroup | Where-Object { Get-LocalGroupMember -Group $_.Name -Member $user.Name -ErrorAction SilentlyContinue } | Select-Object -ExpandProperty Name [PSCustomObject]@{ UserName = $user.Name Groups   = $groups -join ", " } } | Format-Table -AutoSize
      register: local_groups

    - name: Status of user
      ansible.windows.win_powershell:
        script: Get-LocalUser | Where-Object { $_.Enabled -eq $true } | Select-Object -Property Name

