---
- name: Pre Health Check
  hosts: all

  tasks:
    - name: Retrieve Disk Space
      ansible.builtin.gather_facts: 

    - name: Check disk space usage
      ansible.builtin.command:
        cmd: df -h
