---
- name: Pre Health Check
  hosts: all

  tasks:
    - name: Gather Facts on VM
      ansible.builtin.gather_facts: 
      
      # - name: Check disk space usage
      #   ansible.builtin.command:
      #     cmd: df -h

    - name: Generate a Post-Patch HTML report
      ansible.builtin.template:
        src: report.j2
        dest: /home/student/reports/postreport.html


