---
- name: Pre Health Check
  hosts: all

  tasks:
    # - name: Gather Facts on VM
    #   ansible.builtin.gather_facts: 

    # - name: Check disk space usage
    #   ansible.builtin.command:
    #     cmd: df -h

    # - name: List users on the system
    #   ansible.builtin.command:
    #     cmd: cat /etc/passwd
   
    - name: test whether name is capitalize
      ansible.builtin.debug:
        msg: "{{ first | capitalize }} {{ middle | capitalize }} {{ last | capitalize }}"
