- name: Create ACI physical domain and VLAN pool binding
  hosts: aci
  gather_facts: false
  connection: local

  vars:
    username: admin
    password: redhat123
    hostname: 10.69.151.244
    survey_vlan_pool_name: "{{ req_vlan_pool_name }}"
    survey_vlan_block_start: "{{ req_vlan_block_start }}"
    survey_vlan_block_end: "{{ req_vlan_block_end }}"
    survey_domain_name: "{{ req_domain_name }}"
    survey_aep_name: "{{ req_aep_name }}"

  tasks:
    - name: Add a new physical domain
      cisco.aci.aci_domain:
        host: "{{ hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        domain: "{{ survey_domain_name }}"
        domain_type: phys
        state: present
        validate_certs: false

    - name: Add physical domain to VLAN pool binding
      cisco.aci.aci_domain_to_encap_pool:
        host: "{{ hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        domain: "{{ survey_domain_name }}"
        domain_type: phys
        pool: "{{ survey_vlan_pool_name }}"
        pool_type: vlan
        pool_allocation_mode: static
        state: present
        validate_certs: false
