- name: Create new ACI VLAN pool, physical domain, AEP and various bindings
  hosts: aci
  gather_facts: false
  connection: local

  vars:
    username: admin
    password: redhat123
    hostname: 10.69.151.244
#   survey_vlan_pool_name: "{{ req_vlan_pool_name }}"
#    survey_vlan_block_start: "{{ req_vlan_block_start }}"
#    survey_vlan_block_end: "{{ req_vlan_block_end }}"
#    survey_domain_name: "{{ req_domain_name }}"
#    survey_aep_name: "{{ req_aep_name }}"
    survey_vlan_pool_name: production
    survey_vlan_block_start: 10
    survey_vlan_block_end: 20
    survey_domain_name: test1
    survey_aep_name: test1

  tasks:
    - name: Add a new VLAN pool
      cisco.aci.aci_vlan_pool:
        host: "{{ hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        pool: "{{ survey_vlan_pool_name }}"
        pool_allocation_mode: static
        description: "{{ survey_vlan_pool_name }} VLANs"
        state: present
        validate_certs: false
#      delegate_to: localhost

    - name: Add a new VLAN encap block
      cisco.aci.aci_vlan_pool_encap_block:
        host: "{{ hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        pool: "{{ survey_vlan_pool_name }}"
        pool_allocation_mode: static
        block_start: "{{ survey_vlan_block_start }}"
        block_end: "{{ survey_vlan_block_end }}"
        state: present
        validate_certs: false
#      delegate_to: localhost

    - name: Add a new physical domain
      cisco.aci.aci_domain:
        host: "{{ hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        domain: "{{ survey_domain_name }}"
        domain_type: phys
        state: present
        validate_certs: false

    - name: Add a new AEP
      cisco.aci.aci_aep:
        host: "{{ hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        aep: "{{ survey_aep_name }}"
        description: "default for {{ survey_aep_name }}"
        infra_vlan: true
        state: present
        validate_certs: false

    - name: Add physical domain to VLAN pool binding
      cisco.aci.aci_domain_to_encap_pool:
        host: "{{ hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        domain: "{{ survey_domain_name }}"
        domain_type: phys
        pool: "{{ survey_vlan_pool_name }}"
        pool_type: vlan
        pool_allocation_mode: static
        state: present
        validate_certs: false

    - name: Add physical domain to AEP
      cisco.aci.aci_aep_to_domain:
        host: "{{ hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        aep: "{{ survey_aep_name }}"
        domain: "{{ survey_domain_name }}"
        domain_type: phys
        state: present
        validate_certs: false
