- name: NXOS Backup Config 
  hosts: nxos
  gather_facts: no

  tasks:

    - name: Create backup locally
      cisco.nxos.nxos_config:
        backup: yes
        backup_options:
          dir_path: /opt/backups
      register: config_output

    - name: Output the backup information.
      debug:
        var: config_output
