---
- name: Show IOS commands
  hosts: ios
  gather_facts: no

  tasks:
   - name: Gather IOS facts
     cisco.ios.ios_facts:

   - name: Print Hostname
     debug:
      msg: "Hostname is {{ ansible_net_hostname }}"

   - name: Print Version
     debug:
      msg: "Firmware version is {{ ansible_net_version }}"

- name: Show NXOS commands
  hosts: nxos
  gather_facts: no

  tasks:
   - name: Gather NXOS facts
     cisco.nxos.nxos_facts:

   - name: Print Hostname
     debug:
      msg: "Hostname is {{ ansible_net_hostname }}"

   - name: Print Version
     debug:
      msg: "Firmware version is {{ ansible_net_version }}"