---
- name: Automatic Remediation from URL Check
  hosts: all
  sources:
    - name: URL Check
      ansible.eda.url_check:
        urls:
          - https://192.168.122.98
        delay: 10

  rules:
    - name: Web site is down
      condition: event.url_check.status == "down"
      action:
        run_workflow_template:
          name: "Automated Response Web Server EDA"
    